name: Create Github Release

on:
  push:
    tags:
      - "v*"  # Trigger for new versions in tags

permissions:  
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env: 
      RELEASE: tinyTime_${{ github.ref_name }}.zip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release Directory
        run: |
          zip -r ${{ env.RELEASE }} lib/
          zip ${{ env.RELEASE }}  LICENSE README.md

      - name: Release new library version
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          files: ${{ env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}