name: Create Github Release

on:
  push:
    tags:
      - "v*"  # Trigger for new versions in tags

permissions:  
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release Directory
        run: |
          cp -r lib release/
          cp README.md release/
          cp LICENSE release/

      - name: Release new library version
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false  # No manual release
          prerelease: false
          generate_release_notes: true
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}